name: Sitemap Tracker

on:
  schedule:
    - cron: '1 23 * * 0'  # Run every Sunday at 23:01 UTC (Monday 00:01 CET)
  workflow_dispatch:  # Allow manual triggers

jobs:
  track_sitemaps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Run sitemap tracker
      run: python sitemap_tracker.py
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/sitemap_stats.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update sitemap stats" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}