name: Sitemap Tracker

on:
  schedule:
    - cron: '1 23 * * 0'  # Run every Sunday at 23:01 UTC (Monday 00:01 CET)
  workflow_dispatch:  # Allow manual triggers

jobs:
  track_sitemaps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Run sitemap tracker
      run: python sitemap_tracker.py
    - name: Commit and push if changed
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add sitemap_stats.csv
        git commit -m "Update sitemap stats" || exit 0
        git push

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true